"""Training parameter catalogs for the interactive configurator.

Each model family exposes a list of :class:`ParameterDefinition` objects with
documented defaults, ranges, choices and help text. ``parameters_for`` returns
the relevant, task-filtered catalog for a given family/task so the TUI only
shows parameters that apply to the selected model and task.
"""

from __future__ import annotations

from src.utils.cli import ParameterDefinition


# Comprehensive YOLO training parameter definitions for fully customized config
YOLO_TRAINING_PARAMETERS: list[ParameterDefinition] = [
    # Core Training Parameters
    ParameterDefinition(
        name="epochs",
        category="core",
        default=300,
        value_type="int",
        description="Total training iterations",
        help_text="How many times the model sees the entire dataset. More epochs allow for deeper learning but increase training time and risk 'overfitting' (memorizing data). \n\n[bold yellow]Practice:[/bold yellow] 100 is good for small tweaks, 300 is standard for most projects, 500+ is for complex datasets where accuracy is still climbing.",
        min_value=1,
        max_value=10000,
    ),
    ParameterDefinition(
        name="patience",
        category="core",
        default=50,
        value_type="int",
        description="Early stopping threshold",
        help_text="Stops training early if the model hasn't improved for this many epochs. Saves time and electricity by not 'beating a dead horse' when the model has plateaued.\n\n[bold yellow]Practice:[/bold yellow] Set to 50 for standard runs. If you have a very noisy dataset, increase to 100 to give it more time to recover from dips.",
        min_value=0,
        max_value=500,
    ),
    ParameterDefinition(
        name="batch",
        category="core",
        default=-1,
        value_type="int",
        description="Images per training step",
        help_text="Number of images processed at once. Larger batches make training faster and gradients 'smoother' but require more GPU memory.\n\n[bold yellow]Practice:[/bold yellow] Keep at -1 (Auto-Batch). It will test your GPU and find the largest size that fits without crashing. Only set manually if you face OOM errors or want specific gradient behavior.",
        min_value=-1,
        max_value=1024,
    ),
    ParameterDefinition(
        name="imgsz",
        category="core",
        default=640,
        value_type="int",
        description="Input resolution (pixels)",
        help_text="The size images are resized to before entering the model. Larger sizes detect tiny objects better but significantly slow down training and use more VRAM.\n\n[bold yellow]Practice:[/bold yellow] 640 is the sweet spot for most. Use 320-416 for mobile/fast apps, or 1280 if you are detecting very small objects like birds in the distance.",
        min_value=32,
        max_value=2048,
    ),
    ParameterDefinition(
        name="device",
        category="hardware",
        default="0",
        value_type="str",
        description="Computation hardware",
        help_text="Where the heavy math happens. '0' is your first GPU. 'cpu' is much slower but works on any machine. 'mps' is for Mac (M1/M2/M3).\n\n[bold yellow]Practice:[/bold yellow] Use '0' if you have an NVIDIA GPU. Use 'mps' on Mac. Only use 'cpu' as a last resort for debugging.",
        allowed_values=[
            "0",
            "0,1",
            "0,1,2,3",
            "cpu",
            "mps",
            "cuda",
            "npu",
            "npu:0",
            "-1",
        ],
    ),
    ParameterDefinition(
        name="workers",
        category="hardware",
        default=8,
        value_type="int",
        description="CPU loading threads",
        help_text="Number of CPU 'helper' processes that prepare images for the GPU. If the GPU is waiting for images, training slows down.\n\n[bold yellow]Practice:[/bold yellow] Usually set to 8. If you see 'DataLoader' warnings or high CPU usage, lower it. If your GPU usage is low (<80%), try raising it.",
        min_value=0,
        max_value=64,
    ),
    ParameterDefinition(
        name="cache",
        category="hardware",
        default=False,
        value_type="bool_or_str",
        description="Dataset RAM caching",
        help_text="Optionally loads the dataset into RAM so the GPU doesn't have to wait for storage. Persistent disk caching is intentionally disabled because uncompressed .npy copies can be much larger than the source images.\n\n[bold yellow]Practice:[/bold yellow] Set to 'ram' only if the dataset comfortably fits in available RAM. Otherwise keep 'False'.",
        allowed_values=["True", "False", "ram"],
    ),
    ParameterDefinition(
        name="optimizer",
        category="optimizer",
        default="auto",
        value_type="str",
        description="Learning algorithm",
        help_text="The 'brain' that decides how to adjust weights. 'SGD' is reliable for large datasets. 'AdamW' is smarter and faster for smaller datasets/complex problems.\n\n[bold yellow]Practice:[/bold yellow] Keep as 'auto' unless you are an expert. YOLO will pick the best one based on your model size and hardware.",
        allowed_values=[
            "auto",
            "SGD",
            "Adam",
            "AdamW",
            "Adamax",
            "NAdam",
            "RAdam",
            "RMSProp",
            "MuSGD",
        ],
    ),
    ParameterDefinition(
        name="lr0",
        category="optimizer",
        default=0.01,
        value_type="float",
        description="Initial learning speed",
        help_text="How big the steps are when the model learns. Too high and the model 'explodes' (errors go to infinity). Too low and it takes forever to learn anything.\n\n[bold yellow]Practice:[/bold yellow] 0.01 is standard. If your loss is not decreasing, try 0.001. If it's decreasing too slowly, try 0.02.",
        min_value=0.000001,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="lrf",
        category="optimizer",
        default=0.01,
        value_type="float",
        description="Final speed factor",
        help_text="The fraction of the starting speed the model uses at the very end of training. Models usually slow down to 'fine-tune' at the end.\n\n[bold yellow]Practice:[/bold yellow] 0.01 is usually perfect. It means the model finishes at 1% of its starting speed.",
        min_value=0.0001,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="momentum",
        category="optimizer",
        default=0.937,
        value_type="float",
        description="Movement inertia",
        help_text="Helps the model keep moving in the same direction, avoiding getting stuck in small 'ruts' in the data. Like a ball rolling down a hill.\n\n[bold yellow]Practice:[/bold yellow] 0.937 is heavily optimized for YOLO. Don't change unless you are doing deep research.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="weight_decay",
        category="optimizer",
        default=0.0005,
        value_type="float",
        description="Weight penalty (L2)",
        help_text="A 'tax' on large weights that forces the model to stay simple and generalize better. Prevents overfitting.\n\n[bold yellow]Practice:[/bold yellow] 0.0005 is standard. Increase to 0.001 if you have very little data and the model is over-memorizing.",
        min_value=0.0,
        max_value=0.1,
    ),
    ParameterDefinition(
        name="warmup_epochs",
        category="optimizer",
        default=3.0,
        value_type="float",
        description="Ramp-up period (epochs)",
        help_text="The number of epochs at the very start where the model 'warms up' by learning very slowly. Prevents early training crashes.\n\n[bold yellow]Practice:[/bold yellow] 3.0 is usually enough. For very large models, you might want 5.0.",
        min_value=0.0,
        max_value=50.0,
    ),
    ParameterDefinition(
        name="warmup_momentum",
        category="optimizer",
        default=0.8,
        value_type="float",
        description="Warmup inertia",
        help_text="The starting inertia during the ramp-up period. Starts low and grows to the full momentum value.\n\n[bold yellow]Practice:[/bold yellow] 0.8 is standard. Rarely needs changing.",
        min_value=0.0,
        max_value=1.0,
    ),
    # Augmentation Parameters
    ParameterDefinition(
        name="hsv_h",
        category="augmentation",
        default=0.015,
        value_type="float",
        description="Color Hue shift",
        help_text="Randomly shifts colors (e.g., making a red object look slightly orange or purple). Helps the model ignore specific color shades.\n\n[bold yellow]Practice:[/bold yellow] Keep small (0.015). Too much will change the 'meaning' of colors (e.g., turning a green light red).",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="hsv_s",
        category="augmentation",
        default=0.7,
        value_type="float",
        description="Color Saturation shift",
        help_text="Randomly makes colors more vivid or more gray. Simulates different camera quality and lighting.\n\n[bold yellow]Practice:[/bold yellow] 0.7 is powerful for real-world robustness.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="hsv_v",
        category="augmentation",
        default=0.4,
        value_type="float",
        description="Color Brightness shift",
        help_text="Randomly makes the image brighter or darker. Simulates sunny vs. cloudy days or indoor lighting.\n\n[bold yellow]Practice:[/bold yellow] 0.4 is a good balance for most outdoor/indoor tasks.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="degrees",
        category="augmentation",
        default=0.0,
        value_type="float",
        description="Random rotation (deg)",
        help_text="Rotates the image randomly. Essential if your camera can be tilted or objects can appear at angles.\n\n[bold yellow]Practice:[/bold yellow] 0.0 for things like cars (which stay upright). 15-30 for top-down views or handheld cameras. 180 for 'orientation-independent' objects like cells under a microscope.",
        min_value=-180.0,
        max_value=180.0,
    ),
    ParameterDefinition(
        name="translate",
        category="augmentation",
        default=0.1,
        value_type="float",
        description="Random translation",
        help_text="Randomly shifts the image up/down/left/right. Teaches the model that objects don't always appear in the center.\n\n[bold yellow]Practice:[/bold yellow] 0.1 (10% shift) is standard. Increase if your objects are often cut off at the edges.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="scale",
        category="augmentation",
        default=0.5,
        value_type="float",
        description="Random scaling (zoom)",
        help_text="Randomly zooms in or out. Critical for detecting objects at different distances.\n\n[bold yellow]Practice:[/bold yellow] 0.5 means zooming between 0.5x and 1.5x. Essential for almost all detection tasks.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="shear",
        category="augmentation",
        default=0.0,
        value_type="float",
        description="Random shear (slant)",
        help_text="Slants the image sideways. Simulates perspective distortion.\n\n[bold yellow]Practice:[/bold yellow] Keep at 0.0 unless you have extreme camera angles (like a high-mounted security camera).",
        min_value=-180.0,
        max_value=180.0,
    ),
    ParameterDefinition(
        name="perspective",
        category="augmentation",
        default=0.0,
        value_type="float",
        description="Perspective distortion",
        help_text="Advanced 3D-like distortion. Simulates objects being closer or further on one side.\n\n[bold yellow]Practice:[/bold yellow] Use sparingly (0.0001 - 0.001) for drone or security footage. High values can make images unreadable.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="flipud",
        category="augmentation",
        default=0.0,
        value_type="float",
        description="Vertical flip prob",
        help_text="Probability of flipping the image upside-down.\n\n[bold yellow]Practice:[/bold yellow] 0.0 for standard cameras (cars don't drive on the ceiling). 0.5 for satellite imagery or microscope views where 'up' doesn't exist.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="fliplr",
        category="augmentation",
        default=0.5,
        value_type="float",
        description="Horizontal flip prob",
        help_text="Probability of mirroring the image horizontally.\n\n[bold yellow]Practice:[/bold yellow] 0.5 is standard. Keep at 0.0 only if left/right orientation is critical (e.g., reading text or identifying left vs right hands).",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="mosaic",
        category="augmentation",
        default=1.0,
        value_type="float",
        description="Mosaic (4-img stitch)",
        help_text="Stitches 4 images into one during training. Forces the model to handle small objects and crowded scenes.\n\n[bold yellow]Practice:[/bold yellow] 1.0 is the 'secret sauce' of YOLO. Almost always leave it on.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="mixup",
        category="augmentation",
        default=0.0,
        value_type="float",
        description="MixUp (ghosting images)",
        help_text="Overlays two images on top of each other. Teaches the model to find objects even when the background is extremely noisy or busy.\n\n[bold yellow]Practice:[/bold yellow] 0.0 is safe for small datasets. Try 0.1 for complex, large datasets where the model needs more 'challenge'.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="copy_paste",
        category="augmentation",
        default=0.0,
        value_type="float",
        description="Copy-paste augmentation",
        help_text="Copies an object from one image and pastes it into another. Great for making the model see rare objects more often.\n\n[bold yellow]Practice:[/bold yellow] Only works well if you have perfect segmentation masks. 0.0 is default.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="auto_augment",
        category="augmentation",
        default="randaugment",
        value_type="str",
        description="Auto-Augment policy",
        help_text="Let the model decide which augmentations to use based on pre-defined scientific policies.\n\n[bold yellow]Practice:[/bold yellow] 'randaugment' is a safe and modern choice that often beats manual tuning.",
        allowed_values=["", "randaugment", "autoaugment", "augmix"],
    ),
    ParameterDefinition(
        name="erasing",
        category="augmentation",
        default=0.4,
        value_type="float",
        description="Random erasing prob",
        help_text="Randomly 'blacks out' parts of an object. Teaches the model to recognize a car even if the front is hidden behind a pole.\n\n[bold yellow]Practice:[/bold yellow] 0.4 is standard for robust detection.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="close_mosaic",
        category="augmentation",
        default=10,
        value_type="int",
        description="Clean-up period (epochs)",
        help_text="Turns off messy augmentations like Mosaic for the last few epochs. Allows the model to 'settle' and fine-tune on clean images.\n\n[bold yellow]Practice:[/bold yellow] 10 is the standard 'cool-down' period.",
        min_value=0,
        max_value=100,
    ),
    # Loss Parameters
    ParameterDefinition(
        name="box",
        category="loss",
        default=7.5,
        value_type="float",
        description="Box location weight",
        help_text="How much the model cares about getting the box coordinates exactly right. Higher = tighter boxes.\n\n[bold yellow]Practice:[/bold yellow] 7.5 is tuned for YOLO. Increase if your boxes are slightly off-center but classification is correct.",
        min_value=0.0,
        max_value=20.0,
    ),
    ParameterDefinition(
        name="cls",
        category="loss",
        default=0.5,
        value_type="float",
        description="Class naming weight",
        help_text="How much the model cares about getting the object type (e.g., 'Dog' vs 'Cat') correct.\n\n[bold yellow]Practice:[/bold yellow] 0.5 is standard. Increase if the boxes are perfect but the labels are wrong.",
        min_value=0.0,
        max_value=10.0,
    ),
    ParameterDefinition(
        name="dfl",
        category="loss",
        default=1.5,
        value_type="float",
        description="Precision tuning weight",
        help_text="Helps the model be more 'confident' about where the edge of a box is. Reduces 'fuzzy' boxes.\n\n[bold yellow]Practice:[/bold yellow] 1.5 is standard. Don't change unless you have extremely blurry or low-res images.",
        min_value=0.0,
        max_value=10.0,
    ),
    # Advanced Parameters
    ParameterDefinition(
        name="amp",
        category="advanced",
        default=True,
        value_type="bool",
        description="Speed boost (AMP)",
        help_text="Uses 'Mixed Precision' to speed up training and save GPU memory by using smaller numbers (FP16) where possible.\n\n[bold yellow]Practice:[/bold yellow] Always leave enabled unless you see strange 'NaN' (infinity) errors in your loss.",
    ),
    ParameterDefinition(
        name="pretrained",
        category="advanced",
        default=True,
        value_type="bool",
        description="Start from COCO weights",
        help_text="Starts the model with knowledge already learned from the COCO dataset (80 common objects). Faster and better.\n\n[bold yellow]Practice:[/bold yellow] Always leave enabled. Only disable if your objects are radically different (e.g., thermal imagery or ultrasound).",
    ),
    ParameterDefinition(
        name="deterministic",
        category="advanced",
        default=False,
        value_type="bool",
        description="Strict reproducibility",
        help_text="Forces the computer to do the math in the exact same order every time. Useful for scientific papers.\n\n[bold yellow]Practice:[/bold yellow] Leave disabled. It can slow down training and usually isn't needed for real-world apps.",
    ),
    ParameterDefinition(
        name="seed",
        category="advanced",
        default=0,
        value_type="int",
        description="Random seed (repro)",
        help_text="The 'starting number' for random transformations. Using the same seed gives the same results.\n\n[bold yellow]Practice:[/bold yellow] Keep at 0 for random. Set a specific number if you are debugging a specific behavior.",
        min_value=0,
        max_value=999999,
    ),
    ParameterDefinition(
        name="rect",
        category="advanced",
        default=False,
        value_type="bool",
        description="Aspect ratio training",
        help_text="Allows images to keep their natural shape (rectangle) instead of being forced into a square.\n\n[bold yellow]Practice:[/bold yellow] Can be slightly faster. Use if your images are all very wide (like panoramic cameras).",
    ),
    ParameterDefinition(
        name="save_period",
        category="advanced",
        default=-1,
        value_type="int",
        description="Auto-save interval",
        help_text="How often to save a 'backup' of the model during training. \n\n[bold yellow]Practice:[/bold yellow] -1 means only save the best and final. Set to 50 if you want to be able to resume after a power cut.",
        min_value=-1,
        max_value=1000,
    ),
    ParameterDefinition(
        name="fraction",
        category="advanced",
        default=1.0,
        value_type="float",
        description="Dataset subset (%)",
        help_text="Allows you to train on only a portion of your data. \n\n[bold yellow]Practice:[/bold yellow] Use 0.1 to quickly check if your training script works before starting a 24-hour run on the full 1.0 set.",
        min_value=0.01,
        max_value=1.0,
    ),
    # Segmentation-specific Parameters
    ParameterDefinition(
        name="overlap_mask",
        category="segmentation",
        default=True,
        value_type="bool",
        description="Allow overlapping masks",
        help_text="[bold cyan]SEGMENTATION ONLY.[/bold cyan] Whether objects can overlap. \n\n[bold yellow]Practice:[/bold yellow] Always True for natural scenes (e.g., one person in front of another).",
    ),
    ParameterDefinition(
        name="mask_ratio",
        category="segmentation",
        default=4,
        value_type="int",
        description="Mask quality ratio",
        help_text="[bold cyan]SEGMENTATION ONLY.[/bold cyan] Lower values = higher mask precision but uses more GPU memory.\n\n[bold yellow]Practice:[/bold yellow] 4 is the industry standard balance.",
        min_value=1,
        max_value=16,
    ),
    # Validation Parameters
    ParameterDefinition(
        name="val",
        category="validation",
        default=True,
        value_type="bool",
        description="Run test-per-epoch",
        help_text="Checks the model's accuracy on unseen data after every epoch. \n\n[bold yellow]Practice:[/bold yellow] Always leave enabled so you can see if the model is actually getting better.",
    ),
    ParameterDefinition(
        name="conf",
        category="validation",
        default=None,
        value_type="optional_float",
        description="Confidence cut-off",
        help_text="How sure the model must be before it reports a detection during tests.\n\n[bold yellow]Practice:[/bold yellow] Leave None for Ultralytics defaults. Use 0.001 for measuring total potential. For real-world usage, you'll likely use 0.25+.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="max_det",
        category="validation",
        default=300,
        value_type="int",
        description="Max items per image",
        help_text="Upper limit on detections per image during testing.\n\n[bold yellow]Practice:[/bold yellow] 300 is plenty. Increase only for 'Where's Waldo' type datasets with thousands of tiny objects.",
        min_value=1,
        max_value=10000,
    ),
    ParameterDefinition(
        name="plots",
        category="validation",
        default=True,
        value_type="bool",
        description="Generate visual charts",
        help_text="Creates nice charts of your loss, precision, and recall after training.\n\n[bold yellow]Practice:[/bold yellow] Always leave enabled; it's the best way to understand your model's performance.",
    ),
    # Additional Advanced Parameters
    ParameterDefinition(
        name="time",
        category="core",
        default=None,
        value_type="float",
        description="Max training hours",
        help_text="Strict time limit for training. The model will save and stop when time runs out, even if epochs aren't finished.\n\n[bold yellow]Practice:[/bold yellow] Useful for cloud platforms where you pay by the hour.",
        min_value=0.0,
        max_value=1000.0,
    ),
    ParameterDefinition(
        name="cos_lr",
        category="optimizer",
        default=False,
        value_type="bool",
        description="Smooth speed decay",
        help_text="Uses a 'Cosine' curve to slow down training speed smoothly instead of a straight line.\n\n[bold yellow]Practice:[/bold yellow] Often leads to slightly better final accuracy by 'landing' more softly on the best result.",
    ),
    ParameterDefinition(
        name="nbs",
        category="loss",
        default=64,
        value_type="int",
        description="Logic batch size",
        help_text="A math trick used to keep learning stable regardless of your hardware's batch size.\n\n[bold yellow]Practice:[/bold yellow] NEVER change this unless you are an AI researcher.",
        min_value=1,
        max_value=1024,
    ),
    ParameterDefinition(
        name="multi_scale",
        category="advanced",
        default=0.0,
        value_type="float",
        description="Multi-size training",
        help_text="Changes the image size slightly every few batches. Teaches the model to be 'size-blind'.\n\n[bold yellow]Practice:[/bold yellow] Set to 0.1 to help the model detect objects at weird distances.",
        min_value=0.0,
        max_value=1.0,
    ),
    ParameterDefinition(
        name="resume",
        category="advanced",
        default=False,
        value_type="bool",
        description="Pick up where I left off",
        help_text="Restarts training from the last saved 'best.pt' or 'last.pt' file.\n\n[bold yellow]Practice:[/bold yellow] Use this if your computer crashed or you had to stop training midway.",
    ),
    ParameterDefinition(
        name="freeze",
        category="advanced",
        default=None,
        value_type="int",
        description="Freeze early layers",
        help_text="Keeps the first N model layers fixed while the detection or segmentation head adapts to your new dataset.\n\n[bold yellow]Practice:[/bold yellow] Leave unset for most fine-tuning. Try 10 for small datasets that are visually similar to the source model's previous data.",
        min_value=0,
        max_value=100,
    ),
    ParameterDefinition(
        name="single_cls",
        category="advanced",
        default=False,
        value_type="bool",
        description="Ignore labels (just detect)",
        help_text="Treats every object as the same type. \n\n[bold yellow]Practice:[/bold yellow] Useful if you just want to find 'anything' (e.g., 'Detect any animal' vs 'Detect dog/cat/bird').",
    ),
]

YOLO_TRAINING_PARAMETERS.extend(
    [
        ParameterDefinition(
            name="save",
            category="output",
            default=True,
            value_type="bool",
            description="Save training outputs",
            help_text="Controls whether Ultralytics writes checkpoints and run artifacts. Disable only for throwaway diagnostics.",
            affects="Affects whether run artifacts are persisted under the selected project/name output directory.",
        ),
        ParameterDefinition(
            name="project",
            category="output",
            default=None,
            value_type="optional_str",
            description="Run output parent folder",
            help_text="Leave unset to use YOLOmatic's default runs folder. Set a folder name or path when you want this run grouped elsewhere.",
            affects="Affects the parent directory used for training outputs.",
        ),
        ParameterDefinition(
            name="name",
            category="output",
            default=None,
            value_type="optional_str",
            description="Run output name",
            help_text="Leave unset to let YOLOmatic generate a timestamped run name. Set this when you need a stable experiment name.",
            affects="Affects the final run directory name inside project.",
        ),
        ParameterDefinition(
            name="exist_ok",
            category="output",
            default=False,
            value_type="bool",
            description="Allow existing run folder",
            help_text="If True, an existing project/name folder can be reused. Keep False to avoid accidentally mixing run artifacts.",
            affects="Affects output directory collision handling before the run starts.",
        ),
        ParameterDefinition(
            name="verbose",
            category="output",
            default=True,
            value_type="bool",
            description="Detailed console logging",
            help_text="Leave enabled when debugging config behavior. Disable when you want quieter logs.",
            affects="Affects how much detail Ultralytics prints during train/val/export operations.",
        ),
        ParameterDefinition(
            name="profile",
            category="advanced",
            default=False,
            value_type="bool",
            description="Profile model speed",
            help_text="Benchmarks model operations during training/export. Useful for deployment research, not regular accuracy tuning.",
            affects="Affects whether Ultralytics collects speed/profile information.",
        ),
        ParameterDefinition(
            name="compile",
            category="advanced",
            default=False,
            value_type="bool_or_str",
            description="Torch compile mode",
            help_text="Use False for compatibility. Try True/default/reduce-overhead/max-autotune only when your PyTorch and GPU stack support torch.compile well.",
            allowed_values=[
                "False",
                "True",
                "default",
                "reduce-overhead",
                "max-autotune",
            ],
            affects="Affects whether PyTorch compiles the model graph for potential speed gains.",
        ),
        ParameterDefinition(
            name="dropout",
            category="advanced",
            default=0.0,
            value_type="float",
            description="Dropout probability",
            help_text="Mostly useful for classification-style heads. Keep 0.0 for standard detection and segmentation unless you are fighting overfitting.",
            min_value=0.0,
            max_value=1.0,
            affects="Affects model regularization by randomly dropping activations where supported.",
        ),
        ParameterDefinition(
            name="cfg",
            category="advanced",
            default=None,
            value_type="optional_str",
            description="Ultralytics config override path",
            help_text="Optional path to an Ultralytics YAML config. Leave unset unless you have a separate Ultralytics config file to merge.",
            affects="Affects the base Ultralytics runtime configuration loaded before explicit TUI values.",
        ),
        ParameterDefinition(
            name="split",
            category="validation",
            default="val",
            value_type="str",
            description="Dataset split for validation",
            help_text="Use val for normal validation, test for final held-out evaluation, or train only for diagnostics.",
            allowed_values=["train", "val", "test"],
            affects="Affects which dataset split validation metrics are computed on.",
        ),
        ParameterDefinition(
            name="iou",
            category="validation",
            default=0.7,
            value_type="float",
            description="NMS IoU threshold",
            help_text="Higher values keep more overlapping detections. Lower values suppress overlapping boxes/masks more aggressively.",
            min_value=0.0,
            max_value=1.0,
            affects="Affects non-max suppression during validation and prediction-style evaluation.",
        ),
        ParameterDefinition(
            name="save_json",
            category="validation",
            default=False,
            value_type="bool",
            description="Save COCO JSON results",
            help_text="Enable when you need COCO-format evaluation files or external metric tooling.",
            affects="Affects validation output files, not model weights.",
        ),
        ParameterDefinition(
            name="agnostic_nms",
            category="prediction",
            default=False,
            value_type="bool",
            description="Class-agnostic NMS",
            help_text="If True, overlapping detections suppress each other even when their predicted classes differ.",
            affects="Affects post-processing for validation/prediction detections.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="augment",
            category="prediction",
            default=False,
            value_type="bool",
            description="Test-time augmentation",
            help_text="Runs augmented inference passes and merges results. Can improve metrics but slows validation/prediction.",
            affects="Affects validation/prediction inference, not training augmentations.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="classes",
            category="prediction",
            default=None,
            value_type="int_list",
            description="Filter class IDs",
            help_text="Leave None for all classes. Enter comma-separated IDs like 0,2,5 to keep only those classes.",
            affects="Affects which classes are kept during validation/prediction post-processing.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="dnn",
            category="prediction",
            default=False,
            value_type="bool",
            description="Use OpenCV DNN",
            help_text="Only relevant for ONNX inference paths. Keep False for normal PyTorch training and validation.",
            affects="Affects ONNX/OpenCV inference backend selection.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="embed",
            category="prediction",
            default=None,
            value_type="optional_str",
            description="Embedding layer indexes",
            help_text="Advanced feature extraction setting. Leave unset unless you know which layer embeddings you want.",
            affects="Affects whether prediction returns intermediate embeddings.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="retina_masks",
            category="prediction",
            default=False,
            value_type="bool",
            description="High-resolution masks",
            help_text="Segmentation only. Produces masks at original image resolution. Better detail, more memory.",
            affects="Affects segmentation mask output resolution during prediction.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="source",
            category="prediction",
            default=None,
            value_type="optional_str",
            description="Prediction source path",
            help_text="Optional image, folder, video, stream, or URL for prediction workflows. Leave unset for training configs.",
            affects="Affects prediction input source when prediction settings are reused.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="show",
            category="prediction",
            default=False,
            value_type="bool",
            description="Display prediction windows",
            help_text="Shows visual predictions in a window. Usually leave False on servers or inside the TUI.",
            affects="Affects prediction visualization behavior.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="save_frames",
            category="prediction",
            default=False,
            value_type="bool",
            description="Save video frames",
            help_text="For video inference. Saves individual frames in addition to normal outputs.",
            affects="Affects prediction output files for video sources.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="save_txt",
            category="prediction",
            default=False,
            value_type="bool",
            description="Save YOLO text predictions",
            help_text="Writes detection labels to .txt files. Useful for review, pseudo-labeling, and downstream scripts.",
            affects="Affects prediction label output files.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="save_conf",
            category="prediction",
            default=False,
            value_type="bool",
            description="Include confidence in txt",
            help_text="Adds confidence scores to saved prediction .txt files.",
            affects="Affects the contents of saved prediction text labels.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="save_crop",
            category="prediction",
            default=False,
            value_type="bool",
            description="Save cropped detections",
            help_text="Writes each detected object crop as a separate image. Useful for inspection or downstream classifiers.",
            affects="Affects prediction output artifacts and disk usage.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="show_labels",
            category="prediction",
            default=True,
            value_type="bool",
            description="Draw class labels",
            help_text="Controls whether class names appear on rendered predictions.",
            affects="Affects rendered prediction images/videos only.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="show_conf",
            category="prediction",
            default=True,
            value_type="bool",
            description="Draw confidence scores",
            help_text="Controls whether confidence values appear on rendered predictions.",
            affects="Affects rendered prediction images/videos only.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="show_boxes",
            category="prediction",
            default=True,
            value_type="bool",
            description="Draw boxes",
            help_text="Controls whether boxes are drawn around detections in rendered outputs.",
            affects="Affects rendered prediction images/videos only.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="line_width",
            category="prediction",
            default=None,
            value_type="optional_int",
            description="Rendered line width",
            help_text="Leave None for automatic line width. Set a positive integer for fixed box/mask outline thickness.",
            min_value=1,
            max_value=100,
            affects="Affects rendered prediction image/video styling.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="stream_buffer",
            category="prediction",
            default=False,
            value_type="bool",
            description="Buffer stream frames",
            help_text="For live streams. True preserves frames but can add latency; False drops old frames to stay current.",
            affects="Affects live-stream prediction latency and frame handling.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="tracker",
            category="prediction",
            default="botsort.yaml",
            value_type="str",
            description="Tracking config",
            help_text="Used by track mode. botsort.yaml is the default; bytetrack.yaml is the common lighter alternative.",
            allowed_values=["botsort.yaml", "bytetrack.yaml"],
            affects="Affects object tracking behavior when prediction settings are used for tracking.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="vid_stride",
            category="prediction",
            default=1,
            value_type="int",
            description="Video frame stride",
            help_text="1 processes every frame. Higher values skip frames for speed at the cost of temporal detail.",
            min_value=1,
            max_value=1000,
            affects="Affects video prediction speed and temporal coverage.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="visualize",
            category="prediction",
            default=False,
            value_type="bool",
            description="Visualize model features",
            help_text="Debugging feature maps can consume significant disk and memory. Keep False for normal runs.",
            affects="Affects prediction/debug visualization artifacts.",
            config_section="prediction",
        ),
        ParameterDefinition(
            name="format",
            category="export",
            default="onnx",
            value_type="str",
            description="Export format",
            help_text="Choose the deployment artifact type. ONNX is the most portable default; TorchScript is best for PyTorch-only deployment.",
            allowed_values=[
                "torchscript",
                "onnx",
                "openvino",
                "engine",
                "coreml",
                "saved_model",
                "pb",
                "tflite",
                "edgetpu",
                "tfjs",
                "paddle",
                "mnn",
                "ncnn",
                "imx",
                "rknn",
                "executorch",
                "axelera",
            ],
            affects="Affects model.export output format after training completes.",
            config_section="export",
        ),
        ParameterDefinition(
            name="half",
            category="export",
            default=False,
            value_type="bool",
            description="FP16 Half Precision",
            help_text="Converts model weights from FP32 (32-bit floating point) to FP16 (16-bit floating point). This halves the model file size and speeds up inference on modern GPUs. Not recommended for CPU-only deployments as CPU emulation of FP16 can be slower.",
            affects="Reduces model file size by 50% and dramatically improves inference throughput on GPU-capable hardware.",
            config_section="export",
        ),
        ParameterDefinition(
            name="int8",
            category="export",
            default=False,
            value_type="bool",
            description="INT8 Quantization",
            help_text="Quantizes weights and activations to 8-bit integers for extreme acceleration. Best for edge devices like Raspberry Pi, Google Coral Edge TPU, mobile CPUs, or NPUs. It reduces model size by ~75% and maximizes speed, but can cause minor accuracy drops. Note: Requires calibration data (provided via the 'data' parameter) to preserve accuracy.",
            affects="Reduces file size by 75% and maximizes CPU/NPU inference speed, but requires calibration dataset.",
            config_section="export",
        ),
        ParameterDefinition(
            name="dynamic",
            category="export",
            default=False,
            value_type="bool",
            description="Dynamic Batch & Shapes",
            help_text="Enables dynamic input axes for variable batch sizes and image dimensions. Crucial for production deployments (ONNX/TensorRT) where the input batch size or image resolution varies at runtime. If disabled, the exported model will be strictly locked to a fixed batch size and image size (e.g., 1x3x640x640) and will reject other inputs.",
            affects="Allows the exported model to process variable batch sizes and image shapes during inference.",
            config_section="export",
        ),
        ParameterDefinition(
            name="simplify",
            category="export",
            default=True,
            value_type="bool",
            description="Simplify ONNX Graph",
            help_text="Optimizes the ONNX graph structure by folding constants, removing redundant operations, and fusing constant nodes using 'onnx-simplifier'. Highly recommended for ONNX exports to ensure optimal speed, smaller files, and better compatibility with inference engines.",
            affects="Fuses redundant graph operations, improving ONNX/TensorRT deployment stability and speed.",
            config_section="export",
        ),
        ParameterDefinition(
            name="opset",
            category="export",
            default=None,
            value_type="optional_int",
            description="ONNX Opset Version",
            help_text="Specifies the ONNX operator set version to use. Higher opset versions support more advanced layer translations and optimizations, but might not be compatible with older inference engines. Opset 17 is standard; reduce to 11/12 only for legacy backends.",
            min_value=7,
            max_value=25,
            affects="Controls compatibility with older/newer inference engine versions (e.g., ONNX Runtime, TensorRT).",
            config_section="export",
        ),
        ParameterDefinition(
            name="optimize",
            category="export",
            default=True,
            value_type="bool",
            description="Runtime Optimizations",
            help_text="Enables target-specific compiler optimization passes. For TorchScript, this applies mobile JIT optimizations for mobile deployment (Lite Interpreter). For other backends, it can enable higher level compiler optimizations.",
            affects="Invokes additional optimization passes depending on the target export format.",
            config_section="export",
        ),
        ParameterDefinition(
            name="keras",
            category="export",
            default=False,
            value_type="bool",
            description="Use Keras Layers",
            help_text="Forces TensorFlow SavedModel exports to use Keras-compatible layers. Enable this if you plan to import the model back into a Keras training/inference pipeline. Leave disabled for standard deployment in TensorFlow Serving.",
            affects="Changes internal TF SavedModel node structures to match the Keras framework format.",
            config_section="export",
        ),
        ParameterDefinition(
            name="nms",
            category="export",
            default=True,
            value_type="bool",
            description="Include NMS in Graph",
            help_text="Embeds Non-Maximum Suppression (NMS) directly into the exported model graph (supported by CoreML, TensorRT, etc.). When enabled, the model returns filtered bounding box detections directly. When disabled, raw network outputs are returned, requiring client-side NMS.",
            affects="Moves bounding box filtering from client application code into the model itself.",
            config_section="export",
        ),
        ParameterDefinition(
            name="end2end",
            category="export",
            default=None,
            value_type="optional_bool",
            description="End-to-End Export",
            help_text="Enables end-to-end export where supported. If enabled, the model exports with both image pre-processing (scaling, normalization) and post-processing (NMS, box conversion) embedded in the computational graph.",
            affects="Embeds both pre-processing and post-processing steps directly inside the exported graph.",
            config_section="export",
        ),
        ParameterDefinition(
            name="workspace",
            category="export",
            default=None,
            value_type="optional_float",
            description="TensorRT Workspace Size (GB)",
            help_text="Sets the maximum temporary GPU memory (in GB) allocated for TensorRT engine building. A larger workspace allows the TensorRT compiler to explore more high-performance kernels (tactics), leading to a faster final engine. This is compile-time only and does not increase inference memory usage.",
            min_value=0.0,
            max_value=1024.0,
            affects="Gives the TensorRT compiler more memory to search for optimal hardware-level kernels.",
            config_section="export",
        ),
        ParameterDefinition(
            name="warmup_bias_lr",
            category="optimizer",
            default=0.1,
            value_type="float",
            description="Warmup bias learning rate",
            help_text="Initial bias learning rate during warmup. Keep default unless tuning early training instability.",
            min_value=0.0,
            max_value=10.0,
            affects="Affects optimizer bias learning rate during warmup.",
        ),
        ParameterDefinition(
            name="cls_pw",
            category="loss",
            default=0.0,
            value_type="float",
            description="Class loss positive weight",
            help_text="Advanced class-loss weighting. Leave default unless you are matching a specific Ultralytics experiment.",
            min_value=0.0,
            max_value=100.0,
            affects="Affects class loss weighting where supported.",
        ),
        ParameterDefinition(
            name="pose",
            category="loss",
            default=12.0,
            value_type="float",
            description="Pose loss weight",
            help_text="Pose models only. Detection and segmentation runs normally ignore this.",
            min_value=0.0,
            max_value=100.0,
            affects="Affects pose keypoint loss weighting for pose models.",
        ),
        ParameterDefinition(
            name="kobj",
            category="loss",
            default=1.0,
            value_type="float",
            description="Keypoint objectness weight",
            help_text="Pose models only. Leave default unless tuning pose keypoint confidence behavior.",
            min_value=0.0,
            max_value=100.0,
            affects="Affects pose keypoint/objectness loss weighting where supported.",
        ),
        ParameterDefinition(
            name="rle",
            category="loss",
            default=1.0,
            value_type="float",
            description="Rotated loss weight",
            help_text="Oriented/rotated box workflows only. Leave default for detection and segmentation.",
            min_value=0.0,
            max_value=100.0,
            affects="Affects rotated localization loss where supported.",
        ),
        ParameterDefinition(
            name="angle",
            category="loss",
            default=1.0,
            value_type="float",
            description="Angle loss weight",
            help_text="Oriented bounding-box workflows only. Leave default for normal boxes and masks.",
            min_value=0.0,
            max_value=100.0,
            affects="Affects angle prediction loss where supported.",
        ),
        ParameterDefinition(
            name="bgr",
            category="augmentation",
            default=0.0,
            value_type="float",
            description="BGR channel swap probability",
            help_text="Randomly swaps RGB/BGR channel order. Useful only when deployment cameras or datasets differ in channel ordering.",
            min_value=0.0,
            max_value=1.0,
            affects="Affects color-channel augmentation during training.",
        ),
        ParameterDefinition(
            name="cutmix",
            category="augmentation",
            default=0.0,
            value_type="float",
            description="CutMix probability",
            help_text="Pastes rectangular regions from other images into training images. Adds robustness, but can create unrealistic examples.",
            min_value=0.0,
            max_value=1.0,
            affects="Affects CutMix augmentation probability during training.",
        ),
        ParameterDefinition(
            name="copy_paste_mode",
            category="augmentation",
            default="flip",
            value_type="str",
            description="Copy-paste strategy",
            help_text="Segmentation augmentation strategy. flip mirrors pasted masks; mixup blends pasted content.",
            allowed_values=["flip", "mixup"],
            affects="Affects how copy-paste augmentation places segmentation objects.",
        ),
    ]
)

YOLO_PARAMETER_IMPACTS = {
    "epochs": "Affects total training duration and how many chances the model has to improve before final weights are saved.",
    "patience": "Affects early stopping. Larger values keep training alive through longer validation plateaus.",
    "batch": "Affects GPU memory use, training throughput, and gradient stability for every optimizer step.",
    "imgsz": "Affects input resolution, small-object recall, training speed, and VRAM usage.",
    "device": "Affects where training runs: NVIDIA GPU, CPU, Apple MPS, or other supported accelerators.",
    "workers": "Affects how many CPU loader processes prepare batches before the GPU consumes them.",
    "cache": "Affects dataset loading speed and RAM/disk pressure before and during training.",
    "optimizer": "Affects how model weights are updated from loss gradients at every training step.",
    "lr0": "Affects the first learning-rate value used by the optimizer.",
    "lrf": "Affects the final learning-rate target after the scheduler decays from lr0.",
    "momentum": "Affects how strongly the optimizer carries previous update direction into the next update.",
    "weight_decay": "Affects regularization pressure that discourages overly large weights and overfitting.",
    "warmup_epochs": "Affects how long training starts gently before using the full learning schedule.",
    "warmup_momentum": "Affects optimizer momentum during the warmup phase only.",
    "hsv_h": "Affects color hue augmentation applied to training images.",
    "hsv_s": "Affects color saturation augmentation applied to training images.",
    "hsv_v": "Affects brightness/value augmentation applied to training images.",
    "degrees": "Affects random rotation augmentation applied to training images.",
    "translate": "Affects random horizontal and vertical image shifting during augmentation.",
    "scale": "Affects random zoom in/out augmentation and object scale variety.",
    "shear": "Affects slant/perspective-like geometric augmentation.",
    "perspective": "Affects 3D-style perspective distortion during augmentation.",
    "flipud": "Affects probability of vertical image flipping during training.",
    "fliplr": "Affects probability of horizontal image mirroring during training.",
    "mosaic": "Affects probability of stitching four training images into one augmented image.",
    "mixup": "Affects probability of blending two training images together.",
    "copy_paste": "Affects segmentation copy-paste augmentation for moving masks between images.",
    "auto_augment": "Affects which automated augmentation policy YOLO applies in addition to manual settings.",
    "erasing": "Affects random erasing probability for hiding image regions during training.",
    "close_mosaic": "Affects how many final epochs run without mosaic-style heavy augmentation.",
    "box": "Affects how strongly the loss punishes inaccurate bounding-box locations.",
    "cls": "Affects how strongly the loss punishes wrong class predictions.",
    "dfl": "Affects distribution focal loss, which refines bounding-box edge precision.",
    "amp": "Affects whether mixed precision is used to reduce VRAM use and speed up compatible GPU training.",
    "pretrained": "Affects whether training starts from pretrained weights or from a fresh/random initialization.",
    "deterministic": "Affects reproducibility by forcing deterministic algorithms where supported.",
    "seed": "Affects random initialization and augmentation order for reproducible experiments.",
    "rect": "Affects dataloader batching by grouping rectangular images with similar aspect ratios.",
    "save_period": "Affects checkpoint frequency during training.",
    "fraction": "Affects how much of the dataset is used for training.",
    "overlap_mask": "Affects segmentation mask handling when object masks overlap.",
    "mask_ratio": "Affects segmentation mask resolution and memory cost.",
    "val": "Affects whether validation runs during training to track real generalization.",
    "conf": "Affects validation-time confidence threshold for counting detections.",
    "max_det": "Affects the maximum number of validation detections kept per image.",
    "plots": "Affects whether training and validation plots are generated in the run folder.",
    "time": "Affects the maximum wall-clock training time before YOLO stops.",
    "cos_lr": "Affects the learning-rate scheduler shape across training.",
    "nbs": "Affects nominal batch-size normalization for loss scaling.",
    "multi_scale": "Affects whether training image size changes across batches.",
    "resume": "Affects whether training resumes optimizer/model state from an interrupted run.",
    "freeze": "Affects how many early model layers are locked instead of updated.",
    "single_cls": "Affects class handling by collapsing all labels into one object class.",
}

YOLO_PARAMETER_OPTION_DESCRIPTIONS = {
    "cache": {
        "True": "Cache images in RAM when possible. Fastest, but can exhaust system memory on large datasets.",
        "False": "Do not cache. Safest default when RAM is limited or dataset size is unknown.",
        "ram": "Explicitly cache in RAM. Use only when the dataset comfortably fits in available memory.",
    },
    "optimizer": {
        "auto": "Let Ultralytics choose optimizer settings. Best default for most runs.",
        "SGD": "Classic optimizer with momentum. Reliable on larger datasets and common YOLO baselines.",
        "Adam": "Adaptive optimizer that can converge quickly, but may generalize worse than AdamW.",
        "AdamW": "Adaptive optimizer with decoupled weight decay. Strong choice for smaller or harder datasets.",
        "Adamax": "Adam variant based on the infinity norm. Rarely needed unless testing optimizer behavior.",
        "NAdam": "Adam with Nesterov momentum. Research-oriented alternative for adaptive updates.",
        "RAdam": "Rectified Adam. Can be more stable early in training than plain Adam.",
        "RMSProp": "Adaptive optimizer often used in older CNN workflows. Mostly experimental for YOLO.",
        "MuSGD": "Hybrid SGD/Muon option exposed by YOLOmatic. Use only when the installed trainer supports it.",
    },
    "device": {
        "0": "Use the first CUDA GPU.",
        "0,1": "Use two CUDA GPUs when distributed/multi-GPU training is available.",
        "0,1,2,3": "Use four CUDA GPUs when distributed/multi-GPU training is available.",
        "cpu": "Run on CPU. Slow, but useful for debugging or systems without accelerators.",
        "mps": "Use Apple Silicon Metal acceleration.",
        "cuda": "Let PyTorch target CUDA without naming a specific GPU index.",
        "npu": "Use a supported Neural Processing Unit backend.",
        "npu:0": "Use the first supported NPU device.",
        "-1": "Ask Ultralytics to auto-select an idle GPU when supported.",
    },
    "auto_augment": {
        "": "Disable automatic augmentation policy selection.",
        "randaugment": "Modern default policy that randomly samples augmentation operations.",
        "autoaugment": "Policy learned from prior search. Useful for controlled experiments.",
        "augmix": "Blends augmentation chains to improve robustness under visual corruption.",
    },
    "compile": {
        "False": "Disable torch.compile. Safest and most compatible.",
        "True": "Enable torch.compile with PyTorch defaults.",
        "default": "Use PyTorch's default compile mode.",
        "reduce-overhead": "Favor lower runtime overhead. Useful for repeated inference or stable training shapes.",
        "max-autotune": "Spend more compile time searching for faster kernels. Best only for long runs.",
    },
    "copy_paste_mode": {
        "flip": "Mirror copied segmentation objects before pasting.",
        "mixup": "Blend copied objects into the target image.",
    },
    "format": {
        "torchscript": "PyTorch deployment with TorchScript.",
        "onnx": "Portable export for ONNX Runtime and many deployment systems.",
        "openvino": "Intel OpenVINO deployment.",
        "engine": "TensorRT engine for NVIDIA deployment.",
        "coreml": "Apple Core ML deployment.",
        "saved_model": "TensorFlow SavedModel export.",
        "pb": "TensorFlow GraphDef export.",
        "tflite": "TensorFlow Lite export.",
        "edgetpu": "TensorFlow Lite Edge TPU export.",
        "tfjs": "TensorFlow.js browser/server export.",
        "paddle": "PaddlePaddle export.",
        "mnn": "MNN mobile/edge export.",
        "ncnn": "NCNN mobile/edge export.",
        "imx": "NXP i.MX deployment export.",
        "rknn": "Rockchip RKNN deployment export.",
        "executorch": "ExecuTorch deployment export.",
        "axelera": "Axelera AI deployment export.",
    },
    "half": {
        "True": "Export with FP16 weights. High speedup on GPUs, half the storage size.",
        "False": "Export with standard FP32 weights. Safest general compatibility, larger file size.",
    },
    "int8": {
        "True": "Quantize to 8-bit integer. Maximum speed on edge/CPU hardware, requires calibration dataset.",
        "False": "Disable INT8 quantization. Keeps floating-point weights (FP16/FP32).",
    },
    "dynamic": {
        "True": "Enable dynamic axes. Flexible batch and image sizes during runtime prediction.",
        "False": "Lock to fixed batch and image size. Slightly faster compilation and minor optimizations.",
    },
    "simplify": {
        "True": "Simplify the model graph. Recommended for clean and fast ONNX models.",
        "False": "Export the raw, un-optimized computational graph.",
    },
    "nms": {
        "True": "Embed NMS. Model outputs final, filtered detections directly.",
        "False": "Exclude NMS. Model outputs raw tensors; post-processing must be done in client code.",
    },
    "keras": {
        "True": "Use Keras wrappers. Best for integration into Keras-based Python pipelines.",
        "False": "Use standard raw TensorFlow graph structures.",
    },
    "optimize": {
        "True": "Enable backend-specific compilation/mobile optimizations.",
        "False": "Disable extra optimizations, exporting the graph in its standard form.",
    },
    "end2end": {
        "True": "Embed both pre-processing and post-processing steps directly inside the exported graph.",
        "False": "Disable end-to-end embedding. Output raw model outputs.",
    },
    "split": {
        "train": "Evaluate on the training split. Useful only for diagnostics.",
        "val": "Evaluate on the validation split. Normal default.",
        "test": "Evaluate on the held-out test split when one exists.",
    },
    "tracker": {
        "botsort.yaml": "Default BoT-SORT tracker, generally stronger but heavier.",
        "bytetrack.yaml": "ByteTrack tracker, often simpler and faster.",
    },
}

for parameter in YOLO_TRAINING_PARAMETERS:
    parameter.affects = YOLO_PARAMETER_IMPACTS.get(parameter.name, parameter.affects)
    parameter.option_descriptions = YOLO_PARAMETER_OPTION_DESCRIPTIONS.get(
        parameter.name,
        parameter.option_descriptions,
    )


# ---------------------------------------------------------------------------
# RF-DETR training parameters (Roboflow rfdetr library)
# Sourced from https://rfdetr.roboflow.com/latest/learn/train/training-parameters/
# All keys map directly to RFDETR*.train(**kwargs) and are written to the
# ``training`` config section consumed by src/trainers/rfdetr_trainer.py.
# ---------------------------------------------------------------------------
RFDETR_TRAINING_PARAMETERS: list[ParameterDefinition] = [
    ParameterDefinition(
        name="epochs",
        category="core",
        default=100,
        value_type="int",
        description="Total training epochs",
        help_text="Complete passes over the training data.\n\n[bold yellow]Practice:[/bold yellow] 100 is the RF-DETR default; reduce for quick fine-tunes, increase for large datasets.",
        min_value=1,
        max_value=2000,
        affects="Affects total training duration and convergence.",
        config_section="training",
    ),
    ParameterDefinition(
        name="batch_size",
        category="core",
        default=4,
        value_type="int",
        description="Images per step",
        help_text="Samples per iteration. Balance with grad_accum_steps so effective batch = batch_size * grad_accum_steps.\n\n[bold yellow]Practice:[/bold yellow] Lower if you hit out-of-memory; raise on large GPUs.",
        min_value=1,
        max_value=256,
        affects="Affects GPU memory use and gradient stability.",
        config_section="training",
    ),
    ParameterDefinition(
        name="grad_accum_steps",
        category="core",
        default=4,
        value_type="int",
        description="Gradient accumulation",
        help_text="Accumulates gradients over N mini-batches before an optimizer step, simulating a larger batch without extra memory.\n\n[bold yellow]Practice:[/bold yellow] Keep batch_size * grad_accum_steps near 16 for stable training.",
        min_value=1,
        max_value=64,
        affects="Affects effective batch size and gradient smoothness.",
        config_section="training",
    ),
    ParameterDefinition(
        name="resolution",
        category="core",
        default=640,
        value_type="int",
        description="Input resolution (px)",
        help_text="Square input size. Higher improves accuracy but costs memory. Must be a multiple of 32 for detection, and 24 or 12 for segmentation.\n\n[bold yellow]Practice:[/bold yellow] Use the variant's recommended resolution unless tuning speed/accuracy.",
        min_value=64,
        max_value=2048,
        affects="Affects accuracy, small-object recall, speed, and VRAM.",
        config_section="training",
    ),
    ParameterDefinition(
        name="lr",
        category="optimizer",
        default=1.0e-4,
        value_type="float",
        description="Base learning rate",
        help_text="Primary learning rate for the detection/segmentation head and most components.",
        min_value=1.0e-7,
        max_value=1.0,
        affects="Affects the main optimizer step size.",
        config_section="training",
    ),
    ParameterDefinition(
        name="lr_encoder",
        category="optimizer",
        default=1.5e-4,
        value_type="float",
        description="Encoder learning rate",
        help_text="Backbone/encoder learning rate, usually kept conservative for fine-tuning a pretrained backbone.",
        min_value=1.0e-7,
        max_value=1.0,
        affects="Affects how fast the pretrained backbone adapts.",
        config_section="training",
    ),
    ParameterDefinition(
        name="lr_scheduler",
        category="optimizer",
        default="step",
        value_type="str",
        description="LR schedule",
        help_text="'step' decays the learning rate at a drop point; 'cosine' anneals smoothly to a floor.",
        allowed_values=["step", "cosine"],
        affects="Affects the learning-rate curve across training.",
        config_section="training",
        option_descriptions={
            "step": "Decay the learning rate at a fixed drop point. Stable default.",
            "cosine": "Smoothly anneal the learning rate toward lr_min_factor.",
        },
    ),
    ParameterDefinition(
        name="warmup_epochs",
        category="optimizer",
        default=0.0,
        value_type="float",
        description="LR warmup epochs",
        help_text="Linear learning-rate warmup duration at the start of training.",
        min_value=0.0,
        max_value=50.0,
        affects="Affects training stability in the first epochs.",
        config_section="training",
    ),
    ParameterDefinition(
        name="weight_decay",
        category="optimizer",
        default=1.0e-4,
        value_type="float",
        description="Weight decay",
        help_text="L2 regularization coefficient that discourages large weights and overfitting.",
        min_value=0.0,
        max_value=1.0,
        affects="Affects regularization pressure.",
        config_section="training",
    ),
    ParameterDefinition(
        name="drop_path",
        category="optimizer",
        default=0.0,
        value_type="float",
        description="Stochastic depth",
        help_text="Drop-path rate (stochastic depth) for regularizing deeper backbones.",
        min_value=0.0,
        max_value=1.0,
        affects="Affects regularization for large variants.",
        config_section="training",
    ),
    ParameterDefinition(
        name="device",
        category="hardware",
        default="cuda",
        value_type="str",
        description="Computation device",
        help_text="'cuda' for NVIDIA GPU, 'cpu' for CPU, 'mps' for Apple Silicon.",
        allowed_values=["cuda", "cpu", "mps"],
        affects="Affects where training runs.",
        config_section="training",
    ),
    ParameterDefinition(
        name="num_workers",
        category="hardware",
        default=8,
        value_type="int",
        description="Dataloader workers",
        help_text="CPU worker processes that prepare batches for the GPU.",
        min_value=0,
        max_value=64,
        affects="Affects data loading throughput.",
        config_section="training",
    ),
    ParameterDefinition(
        name="gradient_checkpointing",
        category="hardware",
        default=False,
        value_type="bool",
        description="Gradient checkpointing",
        help_text="Recomputes activations during backprop to cut memory at the cost of extra compute.",
        affects="Affects memory use vs. training speed.",
        config_section="training",
    ),
    ParameterDefinition(
        name="use_ema",
        category="core",
        default=True,
        value_type="bool",
        description="EMA weights",
        help_text="Maintains an Exponential Moving Average of weights, usually improving final accuracy.",
        affects="Affects checkpoint quality and stability.",
        config_section="training",
    ),
    ParameterDefinition(
        name="checkpoint_interval",
        category="output",
        default=10,
        value_type="int",
        description="Checkpoint every N epochs",
        help_text="How often to save checkpoints during training.",
        min_value=1,
        max_value=1000,
        affects="Affects checkpoint frequency and disk use.",
        config_section="training",
    ),
    ParameterDefinition(
        name="early_stopping",
        category="core",
        default=True,
        value_type="bool",
        description="Early stopping",
        help_text="Stop training when the validation metric stops improving.",
        affects="Affects whether training halts on plateau.",
        config_section="training",
    ),
    ParameterDefinition(
        name="early_stopping_patience",
        category="core",
        default=10,
        value_type="int",
        description="Early stopping patience",
        help_text="Epochs without improvement before early stopping triggers.",
        min_value=1,
        max_value=500,
        affects="Affects how long plateaus are tolerated.",
        config_section="training",
    ),
    ParameterDefinition(
        name="eval_interval",
        category="validation",
        default=1,
        value_type="int",
        description="Eval every N epochs",
        help_text="How often COCO evaluation runs during training.",
        min_value=1,
        max_value=100,
        affects="Affects validation frequency and runtime.",
        config_section="training",
    ),
    ParameterDefinition(
        name="tensorboard",
        category="output",
        default=True,
        value_type="bool",
        description="TensorBoard logging",
        help_text="Write TensorBoard logs (requires the rfdetr[loggers] extra).",
        affects="Affects logging output.",
        config_section="training",
    ),
    # --- Keypoint / pose-only parameters (RFDETRKeypointPreview) ---
    ParameterDefinition(
        name="num_keypoints_per_class",
        category="keypoint",
        default=[0, 17],
        value_type="int_list",
        description="Keypoints per label slot",
        help_text="Keypoint schema by label slot; 0 means detection-only. Default [0, 17] matches COCO person keypoints.\n\n[bold yellow]Enter as comma-separated ints, e.g. 0,17[/bold yellow]",
        affects="Affects the keypoint head output size per class.",
        config_section="training",
    ),
    ParameterDefinition(
        name="keypoint_flip_pairs",
        category="keypoint",
        default=[],
        value_type="int_list",
        description="L/R flip pairs",
        help_text="Flattened left/right joint index pairs used for horizontal-flip augmentation (e.g. 1,2,3,4 pairs (1,2) and (3,4)).",
        affects="Affects horizontal-flip augmentation correctness for keypoints.",
        config_section="training",
    ),
    ParameterDefinition(
        name="keypoint_l1_loss_coef",
        category="keypoint",
        default=1.0,
        value_type="float",
        description="Keypoint L1 loss",
        help_text="Weight for keypoint coordinate L1 loss.",
        min_value=0.0,
        max_value=100.0,
        affects="Affects keypoint localization accuracy.",
        config_section="training",
    ),
    ParameterDefinition(
        name="keypoint_findable_loss_coef",
        category="keypoint",
        default=1.0,
        value_type="float",
        description="Findable loss weight",
        help_text="Weight for the keypoint findable/objectness loss.",
        min_value=0.0,
        max_value=100.0,
        affects="Affects keypoint presence confidence.",
        config_section="training",
    ),
    ParameterDefinition(
        name="keypoint_visible_loss_coef",
        category="keypoint",
        default=1.0,
        value_type="float",
        description="Visibility loss weight",
        help_text="Weight for the keypoint visibility loss.",
        min_value=0.0,
        max_value=100.0,
        affects="Affects keypoint visibility prediction.",
        config_section="training",
    ),
    ParameterDefinition(
        name="keypoint_nll_loss_coef",
        category="keypoint",
        default=1.0,
        value_type="float",
        description="NLL loss weight",
        help_text="Weight for the keypoint negative-log-likelihood loss (uncertainty modeling).",
        min_value=0.0,
        max_value=100.0,
        affects="Affects keypoint uncertainty estimation.",
        config_section="training",
    ),
]


# ---------------------------------------------------------------------------
# Detectron2 training parameters
# Sourced from Detectron2 config references (SOLVER / MODEL / INPUT / TEST).
# Keys are consumed by build_detectron2_cfg in src/trainers/detectron2_trainer.py
# and written to the ``training`` config section.
# ---------------------------------------------------------------------------
DETECTRON2_TRAINING_PARAMETERS: list[ParameterDefinition] = [
    ParameterDefinition(
        name="max_iter",
        category="core",
        default=3000,
        value_type="int",
        description="Total iterations",
        help_text="Detectron2 trains by iterations, not epochs. SOLVER.MAX_ITER.\n\n[bold yellow]Practice:[/bold yellow] Scale with dataset size; 3000 suits small fine-tunes.",
        min_value=1,
        max_value=1000000,
        affects="Affects total training length (SOLVER.MAX_ITER).",
        config_section="training",
    ),
    ParameterDefinition(
        name="ims_per_batch",
        category="core",
        default=2,
        value_type="int",
        description="Images per batch",
        help_text="Total images per iteration across all GPUs. SOLVER.IMS_PER_BATCH.",
        min_value=1,
        max_value=256,
        affects="Affects memory use and gradient stability.",
        config_section="training",
    ),
    ParameterDefinition(
        name="base_lr",
        category="optimizer",
        default=0.00025,
        value_type="float",
        description="Base learning rate",
        help_text="SOLVER.BASE_LR. The default 0.00025 pairs with ims_per_batch=2; scale linearly with batch size.",
        min_value=1.0e-7,
        max_value=1.0,
        affects="Affects optimizer step size (SOLVER.BASE_LR).",
        config_section="training",
    ),
    ParameterDefinition(
        name="momentum",
        category="optimizer",
        default=0.9,
        value_type="float",
        description="SGD momentum",
        help_text="SOLVER.MOMENTUM for the SGD optimizer.",
        min_value=0.0,
        max_value=1.0,
        affects="Affects how strongly previous updates carry forward.",
        config_section="training",
    ),
    ParameterDefinition(
        name="weight_decay",
        category="optimizer",
        default=0.0001,
        value_type="float",
        description="Weight decay",
        help_text="SOLVER.WEIGHT_DECAY L2 regularization coefficient.",
        min_value=0.0,
        max_value=1.0,
        affects="Affects regularization pressure.",
        config_section="training",
    ),
    ParameterDefinition(
        name="warmup_iters",
        category="optimizer",
        default=1000,
        value_type="int",
        description="Warmup iterations",
        help_text="SOLVER.WARMUP_ITERS — linear LR warmup length at the start of training.",
        min_value=0,
        max_value=100000,
        affects="Affects early-training stability.",
        config_section="training",
    ),
    ParameterDefinition(
        name="gamma",
        category="optimizer",
        default=0.1,
        value_type="float",
        description="LR decay factor",
        help_text="SOLVER.GAMMA — multiplicative LR drop applied at each step milestone.",
        min_value=0.0,
        max_value=1.0,
        affects="Affects learning-rate decay at milestones.",
        config_section="training",
    ),
    ParameterDefinition(
        name="steps",
        category="optimizer",
        default=[],
        value_type="int_list",
        description="LR decay milestones",
        help_text="SOLVER.STEPS — iterations at which the LR is multiplied by gamma. Comma-separated, e.g. 2000,2500. Leave empty for no scheduled decay.",
        affects="Affects when the learning rate drops.",
        config_section="training",
    ),
    ParameterDefinition(
        name="roi_batch_size_per_image",
        category="core",
        default=512,
        value_type="int",
        description="RoI batch / image",
        help_text="MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE — region proposals sampled per image (Faster/Mask R-CNN only).",
        min_value=1,
        max_value=4096,
        affects="Affects RoI head training signal and memory.",
        config_section="training",
    ),
    ParameterDefinition(
        name="score_thresh_test",
        category="prediction",
        default=0.05,
        value_type="float",
        description="Test score threshold",
        help_text="MODEL.ROI_HEADS.SCORE_THRESH_TEST — minimum confidence to keep a detection at inference.",
        min_value=0.0,
        max_value=1.0,
        affects="Affects detections kept during evaluation.",
        config_section="training",
    ),
    ParameterDefinition(
        name="min_size_train",
        category="core",
        default=800,
        value_type="int",
        description="Train short side (px)",
        help_text="INPUT.MIN_SIZE_TRAIN — shorter image edge during training.",
        min_value=64,
        max_value=2048,
        affects="Affects training resolution and small-object recall.",
        config_section="training",
    ),
    ParameterDefinition(
        name="max_size_train",
        category="core",
        default=1333,
        value_type="int",
        description="Train long side (px)",
        help_text="INPUT.MAX_SIZE_TRAIN — maximum longer image edge during training.",
        min_value=64,
        max_value=4096,
        affects="Affects training resolution and memory.",
        config_section="training",
    ),
    ParameterDefinition(
        name="eval_period",
        category="validation",
        default=500,
        value_type="int",
        description="Eval every N iters",
        help_text="TEST.EVAL_PERIOD — run validation every N iterations (0 disables).",
        min_value=0,
        max_value=100000,
        affects="Affects validation frequency.",
        config_section="training",
    ),
    ParameterDefinition(
        name="checkpoint_period",
        category="output",
        default=1000,
        value_type="int",
        description="Checkpoint every N iters",
        help_text="SOLVER.CHECKPOINT_PERIOD — save a checkpoint every N iterations.",
        min_value=1,
        max_value=100000,
        affects="Affects checkpoint frequency and disk use.",
        config_section="training",
    ),
    ParameterDefinition(
        name="num_workers",
        category="hardware",
        default=2,
        value_type="int",
        description="Dataloader workers",
        help_text="DATALOADER.NUM_WORKERS — CPU workers preparing batches.",
        min_value=0,
        max_value=64,
        affects="Affects data loading throughput.",
        config_section="training",
    ),
    ParameterDefinition(
        name="device",
        category="hardware",
        default="cuda",
        value_type="str",
        description="Computation device",
        help_text="MODEL.DEVICE — 'cuda' for NVIDIA GPU or 'cpu'.",
        allowed_values=["cuda", "cpu"],
        affects="Affects where training runs.",
        config_section="training",
    ),
]


# Task-specific parameter name groups used for filtering.
_YOLO_SEG_ONLY = {"overlap_mask", "mask_ratio"}
_YOLO_POSE_ONLY = {"pose", "kobj"}
_RFDETR_KEYPOINT_ONLY = {
    "num_keypoints_per_class",
    "keypoint_flip_pairs",
    "keypoint_l1_loss_coef",
    "keypoint_findable_loss_coef",
    "keypoint_visible_loss_coef",
    "keypoint_nll_loss_coef",
}


def _normalize_task(task: str | None) -> str:
    value = (task or "").strip().lower()
    if value in {"detect", "detection", "bbox", "box"}:
        return "detection"
    if value in {"segment", "segmentation", "seg", "instance_segmentation"}:
        return "segmentation"
    if value in {"pose", "keypoint", "keypoints"}:
        return "pose"
    return value or "detection"


def _filter_yolo_parameters(task: str) -> list[ParameterDefinition]:
    task = _normalize_task(task)
    result: list[ParameterDefinition] = []
    for param in YOLO_TRAINING_PARAMETERS:
        if task != "segmentation" and param.name in _YOLO_SEG_ONLY:
            continue
        if task != "pose" and param.name in _YOLO_POSE_ONLY:
            continue
        result.append(param)
    return result


def _filter_rfdetr_parameters(task: str) -> list[ParameterDefinition]:
    task = _normalize_task(task)
    if task == "pose":
        return list(RFDETR_TRAINING_PARAMETERS)
    return [p for p in RFDETR_TRAINING_PARAMETERS if p.name not in _RFDETR_KEYPOINT_ONLY]


def parameters_for(family: str | None, task: str | None) -> list[ParameterDefinition]:
    """Return the task-filtered parameter catalog for a model family.

    ``family`` is the model-family key (``yolo``/``yolov11``/..., ``rfdetr``,
    ``rfdetr-seg``, ``rfdetr-pose``, ``detectron2``, ``detectron2-seg``) or a
    model name; ``task`` is ``detection``/``segmentation``/``pose``.
    """
    fam = (family or "").strip().lower()
    if fam.startswith("rf-detr") or fam.startswith("rfdetr"):
        return _filter_rfdetr_parameters(task)
    if fam.startswith("detectron2"):
        return list(DETECTRON2_TRAINING_PARAMETERS)
    return _filter_yolo_parameters(task)
