schema_version: 1
name: Original-Minimal
description: Custom augmentation profile
multiplier: 1
seed: 42
include_originals: true
created_at: '2026-05-15T11:32:23'
modified_at: '2026-05-15T11:36:37'
transforms:
- name: HorizontalFlip
  enabled: true
  p: 0.1
- name: VerticalFlip
  enabled: true
  p: 0.1
- name: D4
  enabled: false
  p: 0.5
- name: RandomRotate90
  enabled: true
  p: 0.1
- name: Transpose
  enabled: false
  p: 0.5
- name: Rotate
  enabled: false
  p: 0.5
  limit_low: -15
  limit_high: 15
  border_mode: 4
- name: Affine
  enabled: false
  p: 0.5
- name: RandomScale
  enabled: false
  p: 0.5
- name: RandomCrop
  enabled: false
  p: 0.5
- name: Pad
  enabled: false
  p: 0.5
- name: Perspective
  enabled: false
  p: 0.5
- name: ElasticTransform
  enabled: false
  p: 0.5
- name: GridDistortion
  enabled: false
  p: 0.5
- name: OpticalDistortion
  enabled: false
  p: 0.5
- name: RandomBrightnessContrast
  enabled: false
  p: 0.5
- name: ColorJitter
  enabled: false
  p: 0.5
- name: Solarize
  enabled: false
  p: 0.5
- name: Posterize
  enabled: false
  p: 0.5
- name: Equalize
  enabled: false
  p: 0.5
- name: ToGray
  enabled: false
  p: 0.5
- name: HueSaturationValue
  enabled: false
  p: 0.5
- name: RGBShift
  enabled: false
  p: 0.5
- name: GaussNoise
  enabled: false
  p: 0.5
- name: ISONoise
  enabled: false
  p: 0.5
- name: MultiplicativeNoise
  enabled: false
  p: 0.5
- name: GaussianBlur
  enabled: false
  p: 0.5
- name: MedianBlur
  enabled: false
  p: 0.5
- name: MotionBlur
  enabled: false
  p: 0.5
- name: AdvancedBlur
  enabled: false
  p: 0.5
- name: CLAHE
  enabled: true
  p: 0.1
  clip_limit_low: 1.0
  clip_limit_high: 4.0
- name: Sharpen
  enabled: false
  p: 0.5
  alpha_low: 0.2
  alpha_high: 0.5
  lightness_low: 0.5
  lightness_high: 1.0
- name: UnsharpMask
  enabled: false
  p: 0.5
- name: RandomFog
  enabled: false
  p: 0.5
- name: RandomRain
  enabled: false
  p: 0.5
- name: RandomShadow
  enabled: true
  p: 0.1
  num_shadows_lower: 1
  num_shadows_upper: 2
  shadow_dimension: 5
- name: RandomSunFlare
  enabled: false
  p: 0.5
- name: ImageCompression
  enabled: false
  p: 0.5
- name: Downscale
  enabled: false
  p: 0.5
- name: CoarseDropout
  enabled: false
  p: 0.5
- name: ShotNoise
  enabled: false
  p: 0.5
