schema_version: 1
name: yolo-x-fit
description: optimized for yolo26x for augmentation
multiplier: 3
seed: 42
include_originals: false
created_at: '2026-06-02T15:53:09'
modified_at: '2026-06-18T11:34:27'
transforms:
- name: HorizontalFlip
  enabled: true
  p: 0.2
- name: VerticalFlip
  enabled: true
  p: 0.2
- name: D4
  enabled: false
  p: 0.5
- name: RandomRotate90
  enabled: true
  p: 0.3
- name: Transpose
  enabled: false
  p: 0.5
- name: Rotate
  enabled: true
  p: 0.3
  limit_low: -15
  limit_high: 15
  border_mode: 4
- name: Affine
  enabled: true
  p: 0.3
  shear_low: -10.0
  shear_high: 10.0
  scale_low: 0.9
  scale_high: 1.1
- name: RandomScale
  enabled: true
  p: 0.5
  scale_limit_low: -0.1
  scale_limit_high: 0.1
- name: RandomCrop
  enabled: false
  p: 0.5
  height: 512
  width: 512
- name: Pad
  enabled: false
  p: 0.5
  padding: 32
- name: Perspective
  enabled: true
  p: 0.5
  scale_low: 0.05
  scale_high: 0.1
- name: ElasticTransform
  enabled: false
  p: 0.5
  alpha: 1.0
  sigma: 50.0
- name: GridDistortion
  enabled: true
  p: 0.5
  num_steps: 5
  distort_low: -0.3
  distort_high: 0.3
- name: OpticalDistortion
  enabled: true
  p: 0.5
  distort_low: -0.05
  distort_high: 0.05
- name: RandomBrightnessContrast
  enabled: true
  p: 0.5
  brightness_limit_low: -0.2
  brightness_limit_high: 0.2
  contrast_limit_low: -0.2
  contrast_limit_high: 0.2
- name: ColorJitter
  enabled: false
  p: 0.5
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.0
- name: Solarize
  enabled: false
  p: 0.5
  threshold_low: 0.0
  threshold_high: 0.5
- name: Posterize
  enabled: false
  p: 0.5
  num_bits: 4
- name: Equalize
  enabled: false
  p: 0.5
- name: ToGray
  enabled: false
  p: 0.5
- name: HueSaturationValue
  enabled: false
  p: 0.5
  hue_shift_limit: 20
  sat_shift_limit: 30
  val_shift_limit: 20
- name: RGBShift
  enabled: false
  p: 0.5
  r_shift_limit: 20
  g_shift_limit: 20
  b_shift_limit: 20
- name: GaussNoise
  enabled: false
  p: 0.5
  std_range_low: 0.01
  std_range_high: 0.05
- name: ISONoise
  enabled: false
  p: 0.5
  color_shift_low: 0.01
  color_shift_high: 0.05
  intensity_low: 0.1
  intensity_high: 0.5
- name: MultiplicativeNoise
  enabled: false
  p: 0.5
  multiplier_low: 0.9
  multiplier_high: 1.1
- name: GaussianBlur
  enabled: true
  p: 0.5
  blur_limit_low: 3
  blur_limit_high: 7
- name: MedianBlur
  enabled: false
  p: 0.5
  blur_limit_low: 3
  blur_limit_high: 7
- name: MotionBlur
  enabled: false
  p: 0.5
  blur_limit_low: 3
  blur_limit_high: 7
- name: AdvancedBlur
  enabled: false
  p: 0.5
  blur_limit_low: 3
  blur_limit_high: 7
  sigma_x_limit_low: 0.2
  sigma_x_limit_high: 1.0
  sigma_y_limit_low: 0.2
  sigma_y_limit_high: 1.0
- name: CLAHE
  enabled: true
  p: 0.5
  clip_limit_low: 1.0
  clip_limit_high: 4.0
- name: Sharpen
  enabled: true
  p: 0.5
  alpha_low: 0.2
  alpha_high: 0.5
  lightness_low: 0.5
  lightness_high: 1.0
- name: UnsharpMask
  enabled: false
  p: 0.5
  blur_limit_low: 3
  blur_limit_high: 7
  alpha_low: 0.5
  alpha_high: 1.0
- name: RandomFog
  enabled: false
  p: 0.5
  fog_coef_lower: 0.05
  fog_coef_upper: 0.2
- name: RandomRain
  enabled: false
  p: 0.5
  slant_low: -10
  slant_high: 10
  drop_length: 20
  drop_width: 1
- name: RandomShadow
  enabled: false
  p: 0.5
  num_shadows_lower: 1
  num_shadows_upper: 2
  shadow_dimension: 5
- name: RandomSunFlare
  enabled: false
  p: 0.5
  src_radius: 100
  num_flare_circles_low: 6
  num_flare_circles_high: 10
- name: ImageCompression
  enabled: true
  p: 0.5
  quality_low: 70
  quality_high: 100
- name: Downscale
  enabled: true
  p: 0.5
  scale_range_low: 0.25
  scale_range_high: 0.75
- name: CoarseDropout
  enabled: false
  p: 0.5
  num_holes_low: 1
  num_holes_high: 8
  hole_height_low: 8
  hole_height_high: 32
  hole_width_low: 8
  hole_width_high: 32
- name: ShotNoise
  enabled: false
  p: 0.5
  scale_range_low: 0.01
  scale_range_high: 0.1
